server:
  port: 8080
  servlet:
    context-path: /mini-autorizador

spring:
  application:
    name: mini-autorizador
  datasource:
    url: jdbc:h2:mem:mydb
    username: miniautorizador
    password: 123456
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect