server:
  port: 8080
  servlet:
    context-path: /mini-autorizador

spring:
  application:
    name: mini-autorizador
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true